SwEngHomework/SwEngHomework.WebApp/Models/ErrorViewModel.cs
namespace SwEngHomework.WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SwEngHomework/SwEngHomework.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SwEngHomework.WebApp.Models;
using System;
using System.Diagnostics;

namespace SwEngHomework.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            DateTime currentDateTime = DateTime.Now;
            ViewBag.DateTime = ConvertToUniversalIso8601(currentDateTime);
            ViewBag.DisplayLink = false;
            if (DateTime.TryParse(ViewBag.DateTime, out DateTime dateTime))
            {
                int minute = dateTime.Minute;

                ViewBag.DisplayLink = minute % 2 == 0;
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private string ConvertToUniversalIso8601(DateTime dateTime)
        {
            return dateTime.ToUniversalTime().ToString("u").Replace(" ", "T");
        }
    }
}

SwEngHomework/SwEngHomework.WebApp/Controllers/OtherController.cs
using Microsoft.AspNetCore.Mvc;

namespace SwEngHomework.WebApp.Controllers
{
    public class OtherController : Controller
    {
        private readonly ILogger<OtherController> _logger;

        public OtherController(ILogger<OtherController> logger)
        {
            _logger = logger;
        }

        public IActionResult EvenMinute()
        {
            return View();
        }
    }
}

SwEngHomework/SwEngHomework.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" ">
    <h3 class="display-4">Hello and Welcome!</h3>
    <p>Welcome to the WebApp portion of the homework assignment.  For directions, please consult the README.md</p>
    <hr />

    <div>
        <h4> <i>@ViewBag.DateTime</i> </h4>
    </div>
    @if (ViewBag.DisplayLink)
    {
        @Html.ActionLink("Even Minute","EvenMinute","Other",null,new{target="_blank"})
    }
    <hr />
    <div>
        Thank you for very much for taking the time to complete this part of the homework assignment!
    </div>
</div>

SwEngHomework/SwEngHomework.WebApp/Views/Other/EvenMinute.cshtml
@{
    ViewData["Title"] = "Even Minute";
}
<h1>@ViewData["Title"]</h1>

<p>This page should only be accessed from /Home/Index via link when the date time had an even minute.</p>

SwEngHomework/SwEngHomework.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SwEngHomework.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SwEngHomework.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SwEngHomework.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SwEngHomework.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>